# Open Reading Frames
from Utilities.CodonTable import protein_from_rna
from Utilities.DNA_to_RNA import DNA_to_RNA, reverse_complement

dna = "CGTTTGACTGGGGGATATTACCAATATTGACCTTACCTTCGTAGAGCAGTAAACTGTATGGACGGTAAAATTGTAATTCTATAGAATACGGCCGGTGTGACGCATTCCGAGGAGCCTCGCGGAACATGTATGCCGGTCTTAGAAATGTGGGCCCGAGCATGCGCCGCGCAGTTGGAAGCACCACAATTCGAAGGGTGGGCCTTTTACAGACTAGTAGAGCCTGGCCACTTTGTAATTGTACCCGAAACAGGCACGCTGGCGTTAGCATTCCTCCCTGCACGTCCTCGCGCCATACCAGTAGGAACATCAATTTGTGTACATGGCGTTGAAAGATCTCAGTTGGACTTGACAATGGTAGAAGGTCAAAATTGGACAAACGAGTAATAGTTTCACGTCGTTTTTTAGACGCGTTGGTAAGCAAATTAAGGCTATCGGCTAAATGCACTCGCTCTGGTAGGCCATAACTGATTAGCTAATCAGTTATGGCCTACCAGAGCGAGTGCATGATTGAGAACTCATGCGCCGGGTCCACAAGGTCGTCAAATGATCCTTAGTTTCTCGATGAGCGTCACGAACGTTACTCTTGTAAGATCCTTCCCACGTTAGTCCTTCCGCTCCACTGCTCGCAATGAACGAAGAAAGAGAGGTCAAACCCCAGGAACCGAACAGTAAAGACGAATTTGCCGCTCCTTTGTTCTGAGTTGGACAGATACGTGTGACGCCGTGAGGAGCTCCTCAGCATGGAGCCCCGAGTACTGGATAACTGCTTAACTACTATGTTGAAAACCAAGTCTAAGGACTGCCGTCTATCTCATGGAGCGCGCGGGTGCGCTGCAGTTCGAACAGACCCTAAAGTCTTTCAAGTGAGTTACTTGCCACAGACTGCCGGATGACCGTGGCATATTGTGCCGTGTGCGTAAGGATCTGCGCTGCGCCACTGCTCA"
rna = DNA_to_RNA(dna)


def read(rna):
    ss = {}
    for i in range(len(rna) - 2):
        p = protein_from_rna(rna[i:i+3])
        if p == 'M':
            j = i
            sequence = ""
            while j < len(rna) - 2:
                p = protein_from_rna(rna[j:j+3])
                if p == 'Stop':
                    ss[sequence] = 0
                    break
                sequence += p
                j += 3

    return ss


ss = {}

for d in [dna, reverse_complement(dna)]:
    s = read(DNA_to_RNA(d))
    for k in s.keys():
        ss[k] = 0

for k in ss.keys():
    print(k)
